# documentation: https://docs.sonarsource.com/sonarqube-community-build/
# slogan: Code quality and security, under your control
# tags: development,testing,code quality
# logo: svgs/your-service.svg
# port: 9000

services:
  db:
    image: postgres:17
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    hostname: postgresql
    container_name: postgresql
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-sonar}
      - POSTGRES_PASSWORD=${SERVICE_PASSWORD_DB}
      - POSTGRES_DB=sonar
    volumes:
      - sonar_postgresql:/var/lib/postgresql
      - sonar_postgresql_data:/var/lib/postgresql/data

  sonarqube:
    image: sonarqube:lts-community
    hostname: sonarqube
    container_name: sonarqube
    read_only: true
    ulimits:
      nproc: 131072
      nofile:
        soft: 8192
        hard: 131072
    depends_on:
      init:
        condition: service_completed_successfully
      db:
        condition: service_healthy
    environment:
      - SERVICE_FQDN_SONARQUBE_9000
      - SONAR_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONAR_JDBC_USERNAME=${POSTGRES_USER}
      - SONAR_JDBC_PASSWORD=${SERVICE_PASSWORD_DB}
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp

  init:
    image: bash
    privileged: true
    user: root
    entrypoint: ["/bin/sh", "-c"]
    command: "sysctl -w vm.max_map_count=524288 && sysctl -w fs.file-max=131072"

volumes:
  sonarqube_data:
  sonarqube_temp:
  sonarqube_extensions:
  sonarqube_logs:
  sonar_postgresql:
  sonar_postgresql_data:
